SHOW DATABASES;
SHOW SCHEMAS IN DATABASE PM_OEE_DB;
SHOW TABLES IN DATABASE PM_OEE_DB;
SHOW VIEWS IN DATABASE PM_OEE_DB;
SHOW DYNAMIC TABLES IN DATABASE PM_OEE_DB;
SHOW PROCEDURES IN DATABASE PM_OEE_DB;
SHOW FUNCTIONS IN DATABASE PM_OEE_DB;
SHOW CORTEX SEARCH SERVICES IN DATABASE PM_OEE_DB;
