-- OPTIONAL: remove legacy V1 objects before deploying V2.
USE DATABASE PM_OEE_DB;
USE SCHEMA CORE;

DROP ALERT IF EXISTS ALERT_MACHINE02_CRITICAL;
DROP ALERT IF EXISTS ALERT_MACHINE02_VIBRATION_WARNING;
DROP ALERT IF EXISTS ALERT_MACHINE02_THERMAL;
DROP ALERT IF EXISTS ALERT_FLEET_ANOMALY;
DROP ALERT IF EXISTS ALERT_MACHINE03_VIBRATION;
DROP ALERT IF EXISTS HIGH_RISK_ALERT;

DROP TABLE IF EXISTS TFIDF_VOCABULARY;
DROP TABLE IF EXISTS TFIDF_DOC_MAGNITUDES;
DROP TABLE IF EXISTS TFIDF_IDF;
DROP TABLE IF EXISTS RISK_SCORES;
DROP TABLE IF EXISTS MAINTENANCE_TICKETS;

SELECT 'Legacy V1 cleanup complete' AS status;
