-- Jira Worker Heartbeat table for health status monitoring
-- The Local Jira Worker updates this periodically to signal ONLINE status.
-- Streamlit reads this (read-only) to show worker health in the UI.

USE ROLE ACCOUNTADMIN;
USE DATABASE PM_OEE_DB;
USE SCHEMA CORE;

CREATE TABLE IF NOT EXISTS PM_OEE_DB.CORE.JIRA_WORKER_HEARTBEAT (
    WORKER_ID VARCHAR(100) DEFAULT 'LOCAL_JIRA_WORKER_01',
    STATUS VARCHAR(20) DEFAULT 'OFFLINE',
    LAST_HEARTBEAT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    VERSION VARCHAR(50) DEFAULT '1.0.0',
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Seed initial row if empty
INSERT INTO PM_OEE_DB.CORE.JIRA_WORKER_HEARTBEAT (WORKER_ID, STATUS, VERSION)
SELECT 'LOCAL_JIRA_WORKER_01', 'OFFLINE', '1.0.0'
WHERE NOT EXISTS (SELECT 1 FROM PM_OEE_DB.CORE.JIRA_WORKER_HEARTBEAT WHERE WORKER_ID = 'LOCAL_JIRA_WORKER_01');
