-- ====================================================================
-- sql/external_supply_chain_ingestion.sql
-- Ingestion & Conforming Layer for External Supply Chain Data Share
-- Source Database: SNOWFLAKE_SAMPLE_DATA (TPCH_SF1 Data Share)
-- Target Database: PM_OEE_DB.CORE
-- ====================================================================

USE DATABASE PM_OEE_DB;
USE SCHEMA CORE;
USE WAREHOUSE PM_OEE_WH;

-- 1. Create Raw Supply Chain Ingestion Table (Idempotent schema)
CREATE TABLE IF NOT EXISTS PM_OEE_DB.CORE.RAW_EXTERNAL_SUPPLY_CHAIN (
    PART_KEY NUMBER(38,0),
    PART_NAME VARCHAR(100),
    MANUFACTURER VARCHAR(50),
    BRAND VARCHAR(50),
    PART_TYPE VARCHAR(50),
    PART_SIZE NUMBER(38,0),
    RETAIL_PRICE_USD NUMBER(12,2),
    SUPPLIER_KEY NUMBER(38,0),
    SUPPLIER_NAME VARCHAR(50),
    SUPPLIER_PHONE VARCHAR(30),
    AVAILABLE_QUANTITY NUMBER(38,0),
    SUPPLY_COST_USD NUMBER(12,2),
    SOURCE_DATABASE VARCHAR(100) DEFAULT 'SNOWFLAKE_SAMPLE_DATA',
    SOURCE_TABLE VARCHAR(100) DEFAULT 'TPCH_SF1.PARTSUPP',
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Backward-compatibility table alias
CREATE TABLE IF NOT EXISTS PM_OEE_DB.CORE.RAW_MARKETPLACE_SUPPLY_CHAIN (
    PART_KEY NUMBER(38,0),
    PART_NAME VARCHAR(100),
    MANUFACTURER VARCHAR(50),
    BRAND VARCHAR(50),
    PART_TYPE VARCHAR(50),
    PART_SIZE NUMBER(38,0),
    RETAIL_PRICE_USD NUMBER(12,2),
    SUPPLIER_KEY NUMBER(38,0),
    SUPPLIER_NAME VARCHAR(50),
    SUPPLIER_PHONE VARCHAR(30),
    AVAILABLE_QUANTITY NUMBER(38,0),
    SUPPLY_COST_USD NUMBER(12,2),
    SOURCE_DATABASE VARCHAR(100) DEFAULT 'SNOWFLAKE_SAMPLE_DATA',
    SOURCE_TABLE VARCHAR(100) DEFAULT 'TPCH_SF1.PARTSUPP',
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 2. Populate Raw Supply Chain Data (Idempotent MERGE)
MERGE INTO PM_OEE_DB.CORE.RAW_EXTERNAL_SUPPLY_CHAIN target
USING (
    WITH deduped_parts AS (
        SELECT 
            ps.PS_PARTKEY AS PART_KEY,
            p.P_NAME AS PART_NAME,
            p.P_MFGR AS MANUFACTURER,
            p.P_BRAND AS BRAND,
            p.P_TYPE AS PART_TYPE,
            p.P_SIZE AS PART_SIZE,
            p.P_RETAILPRICE AS RETAIL_PRICE_USD,
            s.S_SUPPKEY AS SUPPLIER_KEY,
            s.S_NAME AS SUPPLIER_NAME,
            s.S_PHONE AS SUPPLIER_PHONE,
            ps.PS_AVAILQTY AS AVAILABLE_QUANTITY,
            ps.PS_SUPPLYCOST AS SUPPLY_COST_USD,
            ROW_NUMBER() OVER (
                PARTITION BY ps.PS_PARTKEY, ps.PS_SUPPKEY 
                ORDER BY ps.PS_AVAILQTY DESC
            ) AS rn
        FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP ps
        JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART p ON ps.PS_PARTKEY = p.P_PARTKEY
        JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER s ON ps.PS_SUPPKEY = s.S_SUPPKEY
        WHERE p.P_TYPE LIKE '%STEEL%' 
           OR p.P_TYPE LIKE '%BRASS%' 
           OR p.P_TYPE LIKE '%COPPER%'
           OR p.P_TYPE LIKE '%NICKEL%'
           OR p.P_TYPE LIKE '%TIN%'
    )
    SELECT 
        PART_KEY, PART_NAME, MANUFACTURER, BRAND, PART_TYPE, PART_SIZE, 
        RETAIL_PRICE_USD, SUPPLIER_KEY, SUPPLIER_NAME, SUPPLIER_PHONE, 
        AVAILABLE_QUANTITY, SUPPLY_COST_USD
    FROM deduped_parts
    WHERE rn = 1
    LIMIT 25000
) src
ON target.PART_KEY = src.PART_KEY AND target.SUPPLIER_KEY = src.SUPPLIER_KEY
WHEN MATCHED THEN UPDATE SET
    target.AVAILABLE_QUANTITY = src.AVAILABLE_QUANTITY,
    target.SUPPLY_COST_USD = src.SUPPLY_COST_USD,
    target.INGESTED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    PART_KEY, PART_NAME, MANUFACTURER, BRAND, PART_TYPE, PART_SIZE,
    RETAIL_PRICE_USD, SUPPLIER_KEY, SUPPLIER_NAME, SUPPLIER_PHONE,
    AVAILABLE_QUANTITY, SUPPLY_COST_USD, SOURCE_DATABASE, SOURCE_TABLE, INGESTED_AT
) VALUES (
    src.PART_KEY, src.PART_NAME, src.MANUFACTURER, src.BRAND, src.PART_TYPE, src.PART_SIZE,
    src.RETAIL_PRICE_USD, src.SUPPLIER_KEY, src.SUPPLIER_NAME, src.SUPPLIER_PHONE,
    src.AVAILABLE_QUANTITY, src.SUPPLY_COST_USD, 'SNOWFLAKE_SAMPLE_DATA', 'TPCH_SF1.PARTSUPP', CURRENT_TIMESTAMP()
);

-- Also keep RAW_MARKETPLACE_SUPPLY_CHAIN populated
MERGE INTO PM_OEE_DB.CORE.RAW_MARKETPLACE_SUPPLY_CHAIN target
USING PM_OEE_DB.CORE.RAW_EXTERNAL_SUPPLY_CHAIN src
ON target.PART_KEY = src.PART_KEY AND target.SUPPLIER_KEY = src.SUPPLIER_KEY
WHEN MATCHED THEN UPDATE SET target.INGESTED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    PART_KEY, PART_NAME, MANUFACTURER, BRAND, PART_TYPE, PART_SIZE,
    RETAIL_PRICE_USD, SUPPLIER_KEY, SUPPLIER_NAME, SUPPLIER_PHONE,
    AVAILABLE_QUANTITY, SUPPLY_COST_USD, SOURCE_DATABASE, SOURCE_TABLE, INGESTED_AT
) VALUES (
    src.PART_KEY, src.PART_NAME, src.MANUFACTURER, src.BRAND, src.PART_TYPE, src.PART_SIZE,
    src.RETAIL_PRICE_USD, src.SUPPLIER_KEY, src.SUPPLIER_NAME, src.SUPPLIER_PHONE,
    src.AVAILABLE_QUANTITY, src.SUPPLY_COST_USD, src.SOURCE_DATABASE, src.SOURCE_TABLE, CURRENT_TIMESTAMP()
);

-- 3. Create Conformed External Part Catalog Table
CREATE TABLE IF NOT EXISTS PM_OEE_DB.CORE.EXTERNAL_PART_CATALOG (
    PART_KEY NUMBER(38,0),
    PART_NAME VARCHAR(100),
    MANUFACTURER VARCHAR(50),
    BRAND VARCHAR(50),
    PART_TYPE VARCHAR(50),
    SUPPLIER_COUNT NUMBER(38,0),
    TOTAL_AVAILABLE_UNITS NUMBER(38,0),
    AVG_SUPPLY_COST_USD NUMBER(12,2),
    PREFERRED_SUPPLIER VARCHAR(50),
    PREFERRED_SUPPLIER_PHONE VARCHAR(30),
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 4. Aggregate & Refresh Conformed External Part Catalog
MERGE INTO PM_OEE_DB.CORE.EXTERNAL_PART_CATALOG target
USING (
    SELECT 
        PART_KEY,
        MAX(PART_NAME) AS PART_NAME,
        MAX(MANUFACTURER) AS MANUFACTURER,
        MAX(BRAND) AS BRAND,
        MAX(PART_TYPE) AS PART_TYPE,
        COUNT(DISTINCT SUPPLIER_KEY) AS SUPPLIER_COUNT,
        SUM(AVAILABLE_QUANTITY) AS TOTAL_AVAILABLE_UNITS,
        AVG(SUPPLY_COST_USD) AS AVG_SUPPLY_COST_USD,
        MAX(SUPPLIER_NAME) AS PREFERRED_SUPPLIER,
        MAX(SUPPLIER_PHONE) AS PREFERRED_SUPPLIER_PHONE
    FROM PM_OEE_DB.CORE.RAW_EXTERNAL_SUPPLY_CHAIN
    GROUP BY PART_KEY
) src
ON target.PART_KEY = src.PART_KEY
WHEN MATCHED THEN UPDATE SET
    target.SUPPLIER_COUNT = src.SUPPLIER_COUNT,
    target.TOTAL_AVAILABLE_UNITS = src.TOTAL_AVAILABLE_UNITS,
    target.AVG_SUPPLY_COST_USD = src.AVG_SUPPLY_COST_USD,
    target.LAST_UPDATED = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    PART_KEY, PART_NAME, MANUFACTURER, BRAND, PART_TYPE,
    SUPPLIER_COUNT, TOTAL_AVAILABLE_UNITS, AVG_SUPPLY_COST_USD,
    PREFERRED_SUPPLIER, PREFERRED_SUPPLIER_PHONE, LAST_UPDATED
) VALUES (
    src.PART_KEY, src.PART_NAME, src.MANUFACTURER, src.BRAND, src.PART_TYPE,
    src.SUPPLIER_COUNT, src.TOTAL_AVAILABLE_UNITS, src.AVG_SUPPLY_COST_USD,
    src.PREFERRED_SUPPLIER, src.PREFERRED_SUPPLIER_PHONE, CURRENT_TIMESTAMP()
);

-- Drop old table if existing to replace with backward-compatible view alias
DROP TABLE IF EXISTS PM_OEE_DB.CORE.MARKETPLACE_PART_CATALOG;

-- Create backward-compatibility view MARKETPLACE_PART_CATALOG
CREATE OR REPLACE VIEW PM_OEE_DB.CORE.MARKETPLACE_PART_CATALOG AS
SELECT * FROM PM_OEE_DB.CORE.EXTERNAL_PART_CATALOG;
