-- ====================================================================
-- sql/marketplace_real_ingestion.sql
-- Ingestion & Conforming Layer for Real Snowflake Marketplace Listings
-- Target Database: PM_OEE_DB.CORE
-- ====================================================================

USE DATABASE PM_OEE_DB;
USE SCHEMA CORE;
USE WAREHOUSE PM_OEE_WH;

-- 1. Ingestion Control Table (tracks listing state and last execution)
CREATE TABLE IF NOT EXISTS PM_OEE_DB.CORE.MARKETPLACE_INGESTION_CONTROL (
    CONTROL_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
    SOURCE_DATABASE     VARCHAR(200),
    SOURCE_SCHEMA       VARCHAR(200),
    SOURCE_TABLE        VARCHAR(200),
    SOURCE_LISTING      VARCHAR(200),
    SOURCE_PROVIDER     VARCHAR(200),
    SOURCE_GLOBAL_NAME  VARCHAR(100),
    LAST_INGESTION_TS   TIMESTAMP_NTZ,
    LAST_ROW_COUNT      NUMBER,
    LAST_SCHEMA_HASH    VARCHAR(64),
    STATUS              VARCHAR(30) DEFAULT 'ACTIVE',
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 2. Ingestion Audit Log (records metrics per stage execution)
CREATE TABLE IF NOT EXISTS PM_OEE_DB.CORE.MARKETPLACE_INGESTION_AUDIT (
    AUDIT_ID            NUMBER AUTOINCREMENT PRIMARY KEY,
    RUN_ID              VARCHAR(50),
    SOURCE_DATABASE     VARCHAR(200),
    SOURCE_TABLE        VARCHAR(200),
    STAGE               VARCHAR(50),
    SOURCE_ROW_COUNT    NUMBER,
    TARGET_ROW_COUNT    NUMBER,
    NEW_ROWS            NUMBER DEFAULT 0,
    UPDATED_ROWS        NUMBER DEFAULT 0,
    DUPLICATE_ROWS      NUMBER DEFAULT 0,
    NULL_ROWS           NUMBER DEFAULT 0,
    INVALID_ROWS        NUMBER DEFAULT 0,
    DATA_FRESHNESS_SEC  NUMBER,
    SCHEMA_CHANGED      BOOLEAN DEFAULT FALSE,
    SCHEMA_DIFF         VARCHAR(4000),
    INGESTION_DURATION_MS NUMBER,
    STATUS              VARCHAR(30),
    ERROR_MESSAGE       VARCHAR(4000),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 3. Raw Marketplace Data Landing Table
CREATE TABLE IF NOT EXISTS PM_OEE_DB.CORE.RAW_MARKETPLACE_DATA (
    RECORD_HASH         VARCHAR(64),
    ROW_HASH            VARCHAR(64),
    GEO_ID              VARCHAR(200),
    VARIABLE            VARCHAR(500),
    VARIABLE_NAME       VARCHAR(1000),
    DATE                DATE,
    VALUE               NUMBER(38,12),
    UNIT                VARCHAR(100),
    SOURCE_DATABASE     VARCHAR(200),
    SOURCE_SCHEMA       VARCHAR(200),
    SOURCE_TABLE        VARCHAR(200),
    MARKETPLACE_LISTING VARCHAR(200),
    MARKETPLACE_PROVIDER VARCHAR(200),
    MARKETPLACE_GLOBAL_NAME VARCHAR(100),
    INGESTED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    INGESTION_RUN_ID    VARCHAR(50)
);

ALTER TABLE PM_OEE_DB.CORE.RAW_MARKETPLACE_DATA ADD COLUMN IF NOT EXISTS RECORD_HASH VARCHAR(64);
ALTER TABLE PM_OEE_DB.CORE.RAW_MARKETPLACE_DATA ADD COLUMN IF NOT EXISTS GEO_ID VARCHAR(200);
ALTER TABLE PM_OEE_DB.CORE.RAW_MARKETPLACE_DATA ADD COLUMN IF NOT EXISTS VARIABLE VARCHAR(500);
ALTER TABLE PM_OEE_DB.CORE.RAW_MARKETPLACE_DATA ADD COLUMN IF NOT EXISTS VARIABLE_NAME VARCHAR(1000);
ALTER TABLE PM_OEE_DB.CORE.RAW_MARKETPLACE_DATA ADD COLUMN IF NOT EXISTS DATE DATE;
ALTER TABLE PM_OEE_DB.CORE.RAW_MARKETPLACE_DATA ADD COLUMN IF NOT EXISTS VALUE NUMBER(38,12);
ALTER TABLE PM_OEE_DB.CORE.RAW_MARKETPLACE_DATA ADD COLUMN IF NOT EXISTS UNIT VARCHAR(100);

-- 4. Conformed Marketplace Data Layer
CREATE TABLE IF NOT EXISTS PM_OEE_DB.CORE.MARKETPLACE_CONFORMED_DATA (
    RECORD_HASH         VARCHAR(64),
    REGION              VARCHAR(200),
    MATERIAL_CATEGORY   VARCHAR(200),
    DATA_TYPE           VARCHAR(200),
    METRIC_NAME         VARCHAR(1000),
    OBSERVATION_DATE    DATE,
    PRICE_USD           NUMBER(38,6),
    INDEX_VALUE         NUMBER(38,6),
    RAW_VALUE           NUMBER(38,12),
    UNIT                VARCHAR(100),
    SOURCE_TABLE        VARCHAR(200),
    MARKETPLACE_LISTING VARCHAR(200),
    MARKETPLACE_PROVIDER VARCHAR(200),
    MARKETPLACE_GLOBAL_NAME VARCHAR(100),
    INGESTED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONFORMED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 5. Part & Supplier Enrichment Table (links Marketplace with ERP Spare Parts)
CREATE TABLE IF NOT EXISTS PM_OEE_DB.CORE.MARKETPLACE_PART_SUPPLIER_ENRICHMENT (
    ENRICHMENT_ID       NUMBER AUTOINCREMENT PRIMARY KEY,
    PART_NUMBER         VARCHAR(100),
    MARKETPLACE_PART_ID VARCHAR(200),
    MARKETPLACE_PART_NAME VARCHAR(500),
    MARKETPLACE_SUPPLIER VARCHAR(200),
    SUPPLIER_COUNT      NUMBER,
    TOTAL_AVAILABLE_QTY NUMBER,
    AVG_SUPPLY_COST_USD NUMBER(12,2),
    MIN_SUPPLY_COST_USD NUMBER(12,2),
    PREFERRED_SUPPLIER  VARCHAR(200),
    DATA_SOURCE         VARCHAR(200),
    LISTING_PROVIDER    VARCHAR(200),
    LAST_UPDATED        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
